### ISSUE TITLE
UI Conflicts/Strange Skin

### ISSUE THREAD

**Issue by Covahz** [solaldunckel/SoulbindTalents#3]
It seems to be having a weird conflict that is causing the thing shown in this picture:
https://gyazo.com/1847479ae6689c78df92dbdde7af4175  (look at the bottom, it makes copies of the "soulbinds" text when I reopen it and has the weird panel overlap)

It also gets reskinned by something/doesn't match the wow ui:
https://gyazo.com/c53515744e3482ce2f56f8f9d606e934

**Comment by Covahz** [comment]
This also stays even when every ui/talent interface is closed:
https://gyazo.com/02708188d505f3bde11c6fd73ab6db86

**Comment by solaldunckel** [comment]
Hey.

I think it might be related to ElvUI.
Can you check if it's working with ElvUI disabled? If it doesn't, please send any LUA error you get (you can catch it with BugGrabber/Bugsack).
The skinning thing is def related to ElvUI (the addon basically reskin if ElvUI is loaded to match their skin) but you  have disabled their "reskin" thing. I can probably fix that.

**Comment by Pinki-Banti** [comment]
Hey, 

I don´t use ElvUI and I also have the same problem, once I open my talents and click on the new "Soulbind" button it also stays when I close the ui/talent interface. So I have the bottom bar of "Spec, Talents and Soulbinds" in my chat now.

The one thing I use is XarUI or now called XarMods, but the only thing is does is make my Blizzard ActionBars look cleaner.

Any ideas/fixes?
