### ISSUE TITLE
The addon hasn't been updated to the newest version and throws lua error when opening

### ISSUE THREAD

**Issue by Chzconey** [solaldunckel/SoulbindTalents#5]
8x SoulbindsTalents\SoulbindsTalents-1.0.4.lua:348: attempt to index field 'BackgroundSheen1' (a nil value)
[string "@SoulbindsTalents\SoulbindsTalents-1.0.4.lua"]:348: in function <SoulbindsTalents\SoulbindsTalents.lua:345>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `SetSheenAnimationsPlaying'
[string "@Blizzard_Soulbinds\Blizzard_SoulbindsViewer.lua"]:141: in function `SetBackgroundStateActive'
[string "@Blizzard_Soulbinds\Blizzard_SoulbindsViewer.lua"]:133: in function `UpdateBackgrounds'
[string "@Blizzard_Soulbinds\Blizzard_SoulbindsViewer.lua"]:208: in function `Init'
[string "@Blizzard_Soulbinds\Blizzard_SoulbindsViewer.lua"]:196: in function `OpenSoulbind'
[string "@Blizzard_Soulbinds\Blizzard_SoulbindsViewer.lua"]:190: in function <...dOns\Blizzard_Soulbinds\Blizzard_SoulbindsViewer.lua:179>
[string "=[C]"]: in function `Open'
[string "@Blizzard_Soulbinds\Blizzard_Soulbinds.lua"]:3: in function `?'
[string "@FrameXML\UIParent.lua"]:2254: in function <FrameXML\UIParent.lua:1287>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:367
 Enable = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:294
 UnregisterAllEvents = <function> defined @LibSharedMedia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 EnableModule = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:442
 SecureHook = <function> defined @Bartender4\libs\AceHook-3.0\AceHook-3.0.lua:336
 defaultModuleLibraries = <table> {
 }
 options = <table> {
 }
 RawHookScript = <function> defined @Bartender4\libs\AceHook-3.0\AceHook-3.0.lua:395
 PlayerTalentFrame_Refresh = <function> defined @SoulbindsTalents\SoulbindsTalents.lua:102
 previousTab = 1
 SetupOptions = <function> defined @SoulbindsTalents\SoulbindsTalents.lua:49
 TooltipHook = <function> defined @SoulbindsTalents\SoulbindsTalents.lua:280
 SetDefaultModulePrototype = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
 OnEnable = <function> defined @SoulbindsTalents\SoulbindsTalents.lua:29
 baseName = "SoulbindsTalents"
 SoulbindViewer_OnCloseButtonClicked = <function> defined @SoulbindsTalents\SoulbindsTalents.lua:249
 name = "SoulbindsTalents"
 SetDefaultModuleState = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:387
 IsEnabled = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 SecureHookScript = <function> defined @Bartender4\libs\AceHook-3.0\AceHook-3.0.lua:410
 DisableModule = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:350
 ConduitRank = <function> defined @SoulbindsTalents\SoulbindsTalents.lua:297
 SoulbindViewer_ChangeTab = <function> defined @SoulbindsTalents\SoulbindsTalents.lua:163
 ADDON_LOADED = <function> defined @SoulbindsTalents\SoulbindsTalents.lua:368
 SoulbindViewer_OnHide = <function> defined @SoulbindsTalents\SoulbindsTalents.lua:245
 RegisterMessage = <function> defined @LibSharedMedia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @LibSharedMedia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 SoulbindViewer_OnOpen = <function> defined @SoulbindsTalents\SoulbindsTalents.lua:176
 ConduitTooltip_Rank = <function> defined @SoulbindsTalents\SoulbindsTalents.lua:255
 IsHooked = <function> defined @Bartender4\libs\AceHook-3.0\AceHook-3.0.lua:493
 Disable = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:314
 settings = <table> {
 }
 IsModule = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:468
 db = <table> {
 }
 SendMessage = <function> defined @LibSharedMedia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 hooks = <table> {
 }
 NewModule = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:235
 SetEnabledState = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @Bartender4\libs\AceHook-3.0\AceHook-3.0.lua:274
 enabledState = true
 UnhookAll = <function> defined @Bartender4\libs\AceHook-3.0\AceHook-3.0.lua:477
 RegisterEvent = <function> defined @LibSharedMedia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterAllMessages = <function> defined @LibSharedMedia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 Unhook = <function> defined @Bar

**Comment by solaldunckel** [comment]
It should be fixed in latest release.

**Comment by Chzconey** [comment]
Thanks appreciate your work.
